const express       = require('express');
const cors          = require('cors');
const bodyParser    = require('body-parser');
const helmet        = require('helmet');
const swaggerUi     = require('swagger-ui-express');
const swaggerJsdoc  = require('swagger-jsdoc');

const limiter       = require('./middlewares/rateLimit');

const app = express();

const swaggerOptions = {
    swaggerDefinition: {
        info: {
          title: 'EncryptChat API',
          version: '1.0.0',
          description: 'Document API with autogenerated swagger doc',
        },
        host: 'localhost:3000',
        basePath: '/'
    },
    apis: [
      './routes/v1/user.js',
    ],
}

const swaggerSpecs = swaggerJsdoc(swaggerOptions);

app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpecs));//swagger doc route

app.use(helmet());//Prevent aboout atacks like about XSS

app.use(cors());

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

app.use(limiter);

const user = require('./routes/v1/user');
app.use('/user', user);

module.exports= app;